# Generated by Django 3.2.7 on 2021-09-10 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider_profile', '0002_providerlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerlocation',
            name='price',
            field=models.IntegerField(default=12, max_length=20),
            preserve_default=False,
        ),
    ]
